# Generated by Django 6.0.4 on 2026-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PICKED', 'Picked'), ('NEAR DESTINATION', 'Near Destination'), ('DELIVERED', 'delivered')], default='ASSIGNED', max_length=50)),
                ('delivery_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
